import type { ClaimData } from "./types";

// Demo claim for the GET /api/forms/<insurer> preview route. Mirrors the canonical schema in
// docs/form-field-map.md; kept in sync with .pdfwork/formfill/sample-claim.mjs.
const sampleClaim: ClaimData = {
  agent_name: "ישראל ישראלי",
  policy_number: "40123567",
  insurance_type: "comprehensive",
  claim_type: "own_policy",
  fault: "me",
  insured: {
    first_name: "דנה",
    last_name: "כהן",
    id_number: "302154687",
    birth_date: "01/01/1990",
    street: "הרצל",
    house_no: "12",
    city: "רעננה",
    postal_code: "4350000",
    address_line: "רחוב הרצל ראשון לציון",
    phone: "09-7654321",
    mobile: "054-1234567",
    email: "dana@example.com",
  },
  driver: {
    first_name: "דנה",
    last_name: "כהן",
    id_number: "302154687",
    birth_date: "01/01/1990",
    address_line: "רחוב הרצל ראשון לציון",
    phone: "09-7654321",
    mobile: "054-1234567",
    email: "dana@example.com",
    license_number: "7654321",
    license_type: "B",
    license_date: "01/06/2008",
    license_expiry: "01/06/2028",
    license_origin: "israeli",
    relation_to_insured: "בעל הרכב",
  },
  vehicle: {
    plate: "12-345-67",
    manufacturer: "טויוטה",
    model: "קורולה",
    year: "2020",
    type: "private",
    odometer: "85000",
  },
  accident: {
    date: "22/06/2026",
    time: "14:30",
    location: "צומת אחוזה רעננה",
    area_type: "junction",
    description: "נסעתי ישר דרך הצומת ורכב צד ג' פגע בי מצד ימין",
    passengers: "2",
    trip_type: "private",
    is_paid_transport: false,
    police: { notified: false, station: "", log_number: "" },
  },
  damage: {
    insured_vehicle: "פגיעה בדלת ימנית קדמית ובכנף",
    third_party_vehicle: "נזק בפגוש אחורי",
  },
  garage: { name: "מוסך הסדר רעננה", address: "רעננה", phone: "09-7654321", is_arrangement: true },
  assessor_name: "שמאי אבי לוי",
  third_parties: [
    {
      vehicle_plate: "88-999-00",
      vehicle_type: "private",
      owner_name: "משה לוי",
      driver_name: "משה לוי",
      id_number: "111222333",
      phone: "052-9876543",
      address: "רחוב ויצמן 5 תל אביב",
      insurer: "הראל",
      insurance_type: "comprehensive",
      policy_number: "99887766",
      agent_name: "סוכנות ביטוח כהן",
      damage_description: "נזק בכנף קדמית שמאלית",
    },
  ],
  witnesses: [{ name: "יוסי אברהם", address: "רעננה", phone: "050-1112222" }],
  injured_persons: [
    {
      name: "דנה כהן",
      id_number: "302154687",
      address: "רחוב הרצל ראשון לציון",
      injury_nature: "חבלה קלה בצוואר",
      age: "36",
      birth_date: "01/01/1990",
      hospitalized: false,
      hospital: "",
    },
  ],
  bank_account: { bank: "בנק הפועלים", branch: "601", account_number: "123456" },
  declarations: {
    poa_third_party: true,
    data_consent: true,
    date: "26/06/2026",
    signatory_name: "דנה כהן",
  },
};

export default sampleClaim;
